# Generated by Django 3.2.7 on 2021-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='something',
            field=models.IntegerField(default=1),
        ),
    ]
