# Generated by Django 3.2.7 on 2021-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_value_something'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='drinker',
            field=models.CharField(max_length=50),
        ),
    ]
