# Generated by Django 3.2.7 on 2021-09-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_value_drinker'),
        ('myapp', '0004_alter_value_drinks_num'),
    ]

    operations = [
    ]
