# Generated by Django 3.2.7 on 2021-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20210928_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='something',
        ),
        migrations.AlterField(
            model_name='value',
            name='drinker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='value',
            name='drinks_num',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
